export class GameObject extends createjs.Container {
  constructor(graphic) {
    super();

    if (graphic !== undefined) {
      this.graphic = graphic;
      this.addChild(this.graphic);
    }

    // symbol graphics generated by Adobe Animate come with a nominalBounds which is the dimension of the graphic. But CreateJS uses setBounds and getBounds methods for symbol dimensions. For each graphic, we set the default object bounds to the exported graphics nominalBounds
    let bounds = this.graphic.nominalBounds;
    this.setBounds(bounds.x, bounds.y, bounds.width, bounds.height);
  }
}

export class MoveableGameObject extends GameObject {
  constructor(graphic) {
    super(graphic);

    this.velocity = {
      x: 0,
      y: 0
    };

    this.onGround = false;

    this.on("tick", this.tick);
  }

  tick() {
    this.y += this.velocity.y;
    this.x += this.velocity.x;
  }
}
